/**
 * MTXCAServicePortType.java
 *
 * This file was auto-generated from WSDL
 * by the Apache Axis 1.4 Apr 22, 2006 (06:55:48 PDT) WSDL2Java emitter.
 */

package ar.gov.afip.wsmtxca.service.impl.service;

public interface MTXCAServicePortType extends java.rmi.Remote {
    public ar.gov.afip.wsmtxca.service.impl.service.DummyResponseType dummy() throws java.rmi.RemoteException, ar.gov.afip.wsmtxca.service.impl.service.ExceptionResponseType;
    public ar.gov.afip.wsmtxca.service.impl.service.AutorizarComprobanteResponseType autorizarComprobante(ar.gov.afip.wsmtxca.service.impl.service.AutorizarComprobanteRequestType parameters) throws java.rmi.RemoteException, ar.gov.afip.wsmtxca.service.impl.service.ExceptionResponseType;
    public ar.gov.afip.wsmtxca.service.impl.service.SolicitarCAEAResponseType solicitarCAEA(ar.gov.afip.wsmtxca.service.impl.service.SolicitarCAEARequestType parameters) throws java.rmi.RemoteException, ar.gov.afip.wsmtxca.service.impl.service.ExceptionResponseType;
    public ar.gov.afip.wsmtxca.service.impl.service.InformarComprobanteCAEAResponseType informarComprobanteCAEA(ar.gov.afip.wsmtxca.service.impl.service.InformarComprobanteCAEARequestType parameters) throws java.rmi.RemoteException, ar.gov.afip.wsmtxca.service.impl.service.ExceptionResponseType;
    public ar.gov.afip.wsmtxca.service.impl.service.ConsultarUltimoComprobanteAutorizadoResponseType consultarUltimoComprobanteAutorizado(ar.gov.afip.wsmtxca.service.impl.service.ConsultarUltimoComprobanteAutorizadoRequestType parameters) throws java.rmi.RemoteException, ar.gov.afip.wsmtxca.service.impl.service.ExceptionResponseType;
    public ar.gov.afip.wsmtxca.service.impl.service.ConsultarComprobanteResponseType consultarComprobante(ar.gov.afip.wsmtxca.service.impl.service.ConsultarComprobanteRequestType parameters) throws java.rmi.RemoteException, ar.gov.afip.wsmtxca.service.impl.service.ExceptionResponseType;
    public ar.gov.afip.wsmtxca.service.impl.service.ConsultarTiposComprobanteResponseType consultarTiposComprobante(ar.gov.afip.wsmtxca.service.impl.service.ConsultarTiposComprobanteRequestType parameters) throws java.rmi.RemoteException, ar.gov.afip.wsmtxca.service.impl.service.ExceptionResponseType;
    public ar.gov.afip.wsmtxca.service.impl.service.ConsultarTiposDocumentoResponseType consultarTiposDocumento(ar.gov.afip.wsmtxca.service.impl.service.ConsultarTiposDocumentoRequestType parameters) throws java.rmi.RemoteException, ar.gov.afip.wsmtxca.service.impl.service.ExceptionResponseType;
    public ar.gov.afip.wsmtxca.service.impl.service.ConsultarAlicuotasIVAResponseType consultarAlicuotasIVA(ar.gov.afip.wsmtxca.service.impl.service.ConsultarAlicuotasIVARequestType parameters) throws java.rmi.RemoteException, ar.gov.afip.wsmtxca.service.impl.service.ExceptionResponseType;
    public ar.gov.afip.wsmtxca.service.impl.service.ConsultarCondicionesIVAResponseType consultarCondicionesIVA(ar.gov.afip.wsmtxca.service.impl.service.ConsultarCondicionesIVARequestType parameters) throws java.rmi.RemoteException, ar.gov.afip.wsmtxca.service.impl.service.ExceptionResponseType;
    public ar.gov.afip.wsmtxca.service.impl.service.ConsultarMonedasResponseType consultarMonedas(ar.gov.afip.wsmtxca.service.impl.service.ConsultarMonedasRequestType parameters) throws java.rmi.RemoteException, ar.gov.afip.wsmtxca.service.impl.service.ExceptionResponseType;
    public ar.gov.afip.wsmtxca.service.impl.service.ConsultarCotizacionMonedaResponseType consultarCotizacionMoneda(ar.gov.afip.wsmtxca.service.impl.service.ConsultarCotizacionMonedaRequestType parameters) throws java.rmi.RemoteException, ar.gov.afip.wsmtxca.service.impl.service.ExceptionResponseType;
    public ar.gov.afip.wsmtxca.service.impl.service.ConsultarUnidadesMedidaResponseType consultarUnidadesMedida(ar.gov.afip.wsmtxca.service.impl.service.ConsultarUnidadesMedidaRequestType parameters) throws java.rmi.RemoteException, ar.gov.afip.wsmtxca.service.impl.service.ExceptionResponseType;
    public ar.gov.afip.wsmtxca.service.impl.service.ConsultarTiposTributoResponseType consultarTiposTributo(ar.gov.afip.wsmtxca.service.impl.service.ConsultarTiposTributoRequestType parameters) throws java.rmi.RemoteException, ar.gov.afip.wsmtxca.service.impl.service.ExceptionResponseType;
    public ar.gov.afip.wsmtxca.service.impl.service.ConsultarPuntosVentaResponseType consultarPuntosVenta(ar.gov.afip.wsmtxca.service.impl.service.ConsultarPuntosVentaRequestType parameters) throws java.rmi.RemoteException, ar.gov.afip.wsmtxca.service.impl.service.ExceptionResponseType;
    public ar.gov.afip.wsmtxca.service.impl.service.ConsultarPuntosVentaResponseType consultarPuntosVentaCAE(ar.gov.afip.wsmtxca.service.impl.service.ConsultarPuntosVentaCAERequestType parameters) throws java.rmi.RemoteException, ar.gov.afip.wsmtxca.service.impl.service.ExceptionResponseType;
    public ar.gov.afip.wsmtxca.service.impl.service.ConsultarPuntosVentaResponseType consultarPuntosVentaCAEA(ar.gov.afip.wsmtxca.service.impl.service.ConsultarPuntosVentaCAEARequestType parameters) throws java.rmi.RemoteException, ar.gov.afip.wsmtxca.service.impl.service.ExceptionResponseType;
    public ar.gov.afip.wsmtxca.service.impl.service.InformarCAEANoUtilizadoResponseType informarCAEANoUtilizado(ar.gov.afip.wsmtxca.service.impl.service.InformarCAEANoUtilizadoRequestType parameters) throws java.rmi.RemoteException, ar.gov.afip.wsmtxca.service.impl.service.ExceptionResponseType;
    public ar.gov.afip.wsmtxca.service.impl.service.InformarCAEANoUtilizadoPtoVtaResponseType informarCAEANoUtilizadoPtoVta(ar.gov.afip.wsmtxca.service.impl.service.InformarCAEANoUtilizadoPtoVtaRequestType parameters) throws java.rmi.RemoteException, ar.gov.afip.wsmtxca.service.impl.service.ExceptionResponseType;
    public ar.gov.afip.wsmtxca.service.impl.service.ConsultarPtosVtaCAEANoInformadosResponseType consultarPtosVtaCAEANoInformados(ar.gov.afip.wsmtxca.service.impl.service.ConsultarPtosVtaCAEANoInformadosRequestType parameters) throws java.rmi.RemoteException, ar.gov.afip.wsmtxca.service.impl.service.ExceptionResponseType;
    public ar.gov.afip.wsmtxca.service.impl.service.ConsultarCAEAResponseType consultarCAEA(ar.gov.afip.wsmtxca.service.impl.service.ConsultarCAEARequestType parameters) throws java.rmi.RemoteException, ar.gov.afip.wsmtxca.service.impl.service.ExceptionResponseType;
    public ar.gov.afip.wsmtxca.service.impl.service.ConsultarCAEAEntreFechasResponseType consultarCAEAEntreFechas(ar.gov.afip.wsmtxca.service.impl.service.ConsultarCAEAEntreFechasRequestType parameters) throws java.rmi.RemoteException, ar.gov.afip.wsmtxca.service.impl.service.ExceptionResponseType;
    public ar.gov.afip.wsmtxca.service.impl.service.AutorizarAjusteIVAResponseType autorizarAjusteIVA(ar.gov.afip.wsmtxca.service.impl.service.AutorizarAjusteIVARequestType parameters) throws java.rmi.RemoteException, ar.gov.afip.wsmtxca.service.impl.service.ExceptionResponseType;
    public ar.gov.afip.wsmtxca.service.impl.service.InformarAjusteIVACAEAResponseType informarAjusteIVACAEA(ar.gov.afip.wsmtxca.service.impl.service.InformarAjusteIVACAEARequestType parameters) throws java.rmi.RemoteException, ar.gov.afip.wsmtxca.service.impl.service.ExceptionResponseType;
    public ar.gov.afip.wsmtxca.service.impl.service.ConsultarTiposDatosAdicionalesResponseType consultarTiposDatosAdicionales(ar.gov.afip.wsmtxca.service.impl.service.ConsultarTiposDatosAdicionalesRequestType parameters) throws java.rmi.RemoteException, ar.gov.afip.wsmtxca.service.impl.service.ExceptionResponseType;
}
